manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson/zmk/tree/core/zephyr-v3.0.0-update
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
